before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go get -v 
brew:
  description: "A simple cli app to return certificates from a Vault PKI mount"
  homepage: "https://github.com/petems/vault-cert-info"
  github:
    owner: petems
    name: homebrew-tap
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install "vault-cert-info"
  test: |
    assert_contains "vault-cert-info - A simple cli app to return certificates from a Vault PKI mount", shell_output("#{bin}/vault-cert-info help").strip
builds:
- 
  env:
    - CGO_ENABLED=0
  ldflags: -s -w -X main.gitCommit={{ .ShortCommit }}
  goos:
    - darwin
    - linux
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: petems
    name: vault-cert-info