sudo: false

language: go

before_install:
  - gem install bundler
  - bundle install
  - docker pull vault

matrix:
  allow_failures:
    - go: master

go:
  - 1.14.x
  - master

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
  - go get -u golang.org/x/lint/golint

script:
  - make lint
  - go test -v -race ./...  # Run all the tests with the race detector enabled
  - bundle exec cucumber

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux